version: '3.1'

services:
  backend:
    image: sblog-backend
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - /home/admin/simpleblog-static/static/feed.xml:/backend/feed.xml
      - /home/admin/Projects/simple-blog-data/:/backend/data

  frontend:
    image: sblog-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
