version: '3.1'

services:
  simple-blog:
    image: simple-blog:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /path/to/service.db:/service.db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}