/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ee.fakeplastictrees.blog.codegen.api;

import ee.fakeplastictrees.blog.codegen.model.MediaPost200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0-SNAPSHOT")
@Validated
@Tag(name = "Media", description = "the Media API")
public interface MediaApi {

    /**
     * GET /media/{id}
     * Get a media file
     *
     * @param id Media file id (required)
     * @return File content (status code 200)
     *         or Media file not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "mediaIdGet",
        description = "Get a media file",
        tags = { "Media" },
        responses = {
            @ApiResponse(responseCode = "200", description = "File content", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "404", description = "Media file not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/media/{id}",
        produces = { "application/octet-stream" }
    )
    
    ResponseEntity<org.springframework.core.io.Resource> mediaIdGet(
        @Parameter(name = "id", description = "Media file id", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * POST /media
     * Upload a file
     *
     * @param file  (optional)
     * @return File uploaded successfully (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "mediaPost",
        description = "Upload a file",
        tags = { "Media" },
        responses = {
            @ApiResponse(responseCode = "200", description = "File uploaded successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = MediaPost200Response.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/media",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<MediaPost200Response> mediaPost(
        @Parameter(name = "file", description = "") @RequestPart(value = "file", required = false) MultipartFile file
    );

}
