/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.10.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ee.fakeplastictrees.blog.codegen.api;

import ee.fakeplastictrees.blog.codegen.model.PagePostDto;
import ee.fakeplastictrees.blog.codegen.model.PostDto;
import ee.fakeplastictrees.blog.codegen.model.PostEditorDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.10.0-SNAPSHOT")
@Validated
@Tag(name = "Posts", description = "the Posts API")
public interface PostsApi {

    /**
     * GET /posts/editor
     * Get all posts, both published and drafts
     *
     * @param page Page number (optional, default to 1)
     * @return OK (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsEditorGet",
        description = "Get all posts, both published and drafts",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PagePostDto.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/editor",
        produces = { "application/json" }
    )
    
    ResponseEntity<PagePostDto> postsEditorGet(
        @Parameter(name = "page", description = "Page number", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page
    );


    /**
     * DELETE /posts/editor/{id}
     * Delete an existing post
     *
     * @param id Post id (required)
     * @return OK (status code 200)
     *         or Unauthorized (status code 401)
     *         or Post not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsEditorIdDelete",
        description = "Delete an existing post",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "404", description = "Post not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/posts/editor/{id}"
    )
    
    ResponseEntity<Void> postsEditorIdDelete(
        @Parameter(name = "id", description = "Post id", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * GET /posts/editor/{id}
     * Get a post, whether it&#39;s published or not
     *
     * @param id Post id (required)
     * @return OK (status code 200)
     *         or Unauthorized (status code 401)
     *         or Post not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsEditorIdGet",
        description = "Get a post, whether it's published or not",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDto.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "404", description = "Post not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/editor/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<PostDto> postsEditorIdGet(
        @Parameter(name = "id", description = "Post id", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * PUT /posts/editor/{id}
     * Update an existing post
     *
     * @param id Post id (required)
     * @param postEditorDto  (required)
     * @return OK (status code 200)
     *         or Unauthorized (status code 401)
     *         or Post not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsEditorIdPut",
        description = "Update an existing post",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDto.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "404", description = "Post not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/posts/editor/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<PostDto> postsEditorIdPut(
        @Parameter(name = "id", description = "Post id", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "PostEditorDto", description = "", required = true) @Valid @RequestBody PostEditorDto postEditorDto
    );


    /**
     * POST /posts/editor
     * Create a new post
     *
     * @param postEditorDto  (required)
     * @return OK (status code 201)
     *         or Unauthorized (status code 401)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsEditorPost",
        description = "Create a new post",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "201", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDto.class))
            }),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/posts/editor",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<PostDto> postsEditorPost(
        @Parameter(name = "PostEditorDto", description = "", required = true) @Valid @RequestBody PostEditorDto postEditorDto
    );


    /**
     * GET /posts/published
     * Get published posts
     *
     * @param page Page number (optional, default to 1)
     * @return OK (status code 200)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsPublishedGet",
        description = "Get published posts",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PagePostDto.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/published",
        produces = { "application/json" }
    )
    
    ResponseEntity<PagePostDto> postsPublishedGet(
        @Parameter(name = "page", description = "Page number", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page
    );


    /**
     * GET /posts/published/{id}
     * Get a published post by id
     *
     * @param id Post id (required)
     * @return OK (status code 200)
     *         or Post not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "postsPublishedIdGet",
        description = "Get a published post by id",
        tags = { "Posts" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PostDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Post not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/posts/published/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<PostDto> postsPublishedIdGet(
        @Parameter(name = "id", description = "Post id", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );

}
