apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.media.storage }}
