// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Post struct {
	ID      uuid.UUID
	Title   sql.NullString
	Summary sql.NullString
	Text    sql.NullString
	Date    sql.NullTime
	Visible sql.NullBool
}

type User struct {
	ID       uuid.UUID
	Username string
	Password string
	Active   sql.NullBool
}
