// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Post struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Summary string    `json:"summary"`
	Text    string    `json:"text"`
	Date    time.Time `json:"date"`
	Visible bool      `json:"visible"`
}
