// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Post struct {
	ID       string
	Title    string
	Summary  string
	Text     string
	Date     time.Time
	Visible  bool
	Keywords sql.NullString
}

type User struct {
	ID       string
	Username string
	Password string
	Active   bool
}
