// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const deletePost = `-- name: DeletePost :exec
delete from posts
where id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
select id, title, summary, text, date, visible
from posts
where id = ?
    and visible = ?
`

type GetPostParams struct {
	ID      string `json:"id"`
	Visible bool   `json:"visible"`
}

func (q *Queries) GetPost(ctx context.Context, arg GetPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, arg.ID, arg.Visible)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Summary,
		&i.Text,
		&i.Date,
		&i.Visible,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
select id,
    title,
    summary,
    date,
    visible
from posts
where visible = ?
order by date desc
`

type GetPostsRow struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Summary string    `json:"summary"`
	Date    time.Time `json:"date"`
	Visible bool      `json:"visible"`
}

func (q *Queries) GetPosts(ctx context.Context, visible bool) ([]GetPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, visible)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsRow
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Date,
			&i.Visible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPost = `-- name: InsertPost :exec
insert into posts(id, title, summary, date, visible)
values(?, ?, ?, ?, ?)
`

type InsertPostParams struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Summary string    `json:"summary"`
	Date    time.Time `json:"date"`
	Visible bool      `json:"visible"`
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) error {
	_, err := q.db.ExecContext(ctx, insertPost,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Date,
		arg.Visible,
	)
	return err
}

const updatePost = `-- name: UpdatePost :exec
update posts
set title = ?,
    summary = ?,
    date = ?,
    visible = ?
where id = ?
`

type UpdatePostParams struct {
	Title   string    `json:"title"`
	Summary string    `json:"summary"`
	Date    time.Time `json:"date"`
	Visible bool      `json:"visible"`
	ID      string    `json:"id"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost,
		arg.Title,
		arg.Summary,
		arg.Date,
		arg.Visible,
		arg.ID,
	)
	return err
}
