/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MediaPost200Response
 */
export interface MediaPost200Response {
    /**
     * Id of the media file
     * @type {string}
     * @memberof MediaPost200Response
     */
    id: string;
}

/**
 * Check if a given object implements the MediaPost200Response interface.
 */
export function instanceOfMediaPost200Response(value: object): value is MediaPost200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function MediaPost200ResponseFromJSON(json: any): MediaPost200Response {
    return MediaPost200ResponseFromJSONTyped(json, false);
}

export function MediaPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

  export function MediaPost200ResponseToJSON(json: any): MediaPost200Response {
      return MediaPost200ResponseToJSONTyped(json, false);
  }

  export function MediaPost200ResponseToJSONTyped(value?: MediaPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

