/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostDto
 */
export interface PostDto {
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    text: string;
    /**
     * 
     * @type {Date}
     * @memberof PostDto
     */
    date: Date;
    /**
     * 
     * @type {boolean}
     * @memberof PostDto
     */
    visible: boolean;
}

/**
 * Check if a given object implements the PostDto interface.
 */
export function instanceOfPostDto(value: object): value is PostDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('visible' in value) || value['visible'] === undefined) return false;
    return true;
}

export function PostDtoFromJSON(json: any): PostDto {
    return PostDtoFromJSONTyped(json, false);
}

export function PostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'summary': json['summary'],
        'text': json['text'],
        'date': (new Date(json['date'])),
        'visible': json['visible'],
    };
}

  export function PostDtoToJSON(json: any): PostDto {
      return PostDtoToJSONTyped(json, false);
  }

  export function PostDtoToJSONTyped(value?: PostDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'text': value['text'],
        'date': ((value['date']).toISOString()),
        'visible': value['visible'],
    };
}

