version: "3.8"

services:
  service:
    build: .
    restart: always
    image: simple-blog-service:latest
    ports:
      - 8080:8080
    volumes:
      - /path/to/data/:/data
    env_file:
      - .env
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
