version: "3.8"

services:
  service:
    build: .
    restart: always
    image: simple-blog-service:latest
    ports:
      - 8080:8080
    volumes:
      - /path/to/data/:/data
    env_file:
      - .env
