/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageDto
 */
export interface PageDto {
    /**
     * Current page
     * @type {number}
     * @memberof PageDto
     */
    page: number;
    /**
     * Total pages
     * @type {number}
     * @memberof PageDto
     */
    totalPages: number;
    /**
     * Page items
     * @type {Array<any>}
     * @memberof PageDto
     */
    items: Array<any>;
}

/**
 * Check if a given object implements the PageDto interface.
 */
export function instanceOfPageDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PageDtoFromJSON(json: any): PageDto {
    return PageDtoFromJSONTyped(json, false);
}

export function PageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'totalPages': json['totalPages'],
        'items': json['items'],
    };
}

export function PageDtoToJSON(value?: PageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'totalPages': value.totalPages,
        'items': value.items,
    };
}

