/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTokenDto
 */
export interface UserTokenDto {
    /**
     * 
     * @type {string}
     * @memberof UserTokenDto
     */
    token: string;
    /**
     * 
     * @type {number}
     * @memberof UserTokenDto
     */
    expires: number;
}

/**
 * Check if a given object implements the UserTokenDto interface.
 */
export function instanceOfUserTokenDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "expires" in value;

    return isInstance;
}

export function UserTokenDtoFromJSON(json: any): UserTokenDto {
    return UserTokenDtoFromJSONTyped(json, false);
}

export function UserTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTokenDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expires': json['expires'],
    };
}

export function UserTokenDtoToJSON(value?: UserTokenDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'expires': value.expires,
    };
}

