// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// PostDto defines model for PostDto.
type PostDto struct {
	Date    string `json:"date"`
	Id      string `json:"id"`
	Summary string `json:"summary"`
	Text    string `json:"text"`
	Title   string `json:"title"`
	Visible bool   `json:"visible"`
}

// PostEditorDto defines model for PostEditorDto.
type PostEditorDto struct {
	Date    *string `json:"date,omitempty"`
	Id      *string `json:"id,omitempty"`
	Summary string  `json:"summary"`
	Text    string  `json:"text"`
	Title   string  `json:"title"`
	Visible bool    `json:"visible"`
}

// PostPreviewDto defines model for PostPreviewDto.
type PostPreviewDto struct {
	Date    string `json:"date"`
	Id      string `json:"id"`
	Summary string `json:"summary"`
	Title   string `json:"title"`
	Visible bool   `json:"visible"`
}

// UserTokenDto defines model for UserTokenDto.
type UserTokenDto struct {
	Expires int    `json:"expires"`
	Token   string `json:"token"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostUsersTokenJSONBody defines parameters for PostUsersToken.
type PostUsersTokenJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostPostsEditorJSONRequestBody defines body for PostPostsEditor for application/json ContentType.
type PostPostsEditorJSONRequestBody = PostEditorDto

// PutPostsEditorIdJSONRequestBody defines body for PutPostsEditorId for application/json ContentType.
type PutPostsEditorIdJSONRequestBody = PostEditorDto

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// PostUsersTokenJSONRequestBody defines body for PostUsersToken for application/json ContentType.
type PostUsersTokenJSONRequestBody PostUsersTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /posts/editor)
	GetPostsEditor(c *gin.Context)

	// (POST /posts/editor)
	PostPostsEditor(c *gin.Context)

	// (DELETE /posts/editor/{id})
	DeletePostsEditorId(c *gin.Context, id string)

	// (GET /posts/editor/{id})
	GetPostsEditorId(c *gin.Context, id string)

	// (PUT /posts/editor/{id})
	PutPostsEditorId(c *gin.Context, id string)

	// (GET /posts/published)
	GetPostsPublished(c *gin.Context)

	// (GET /posts/published/{id})
	GetPostsPublishedId(c *gin.Context, id string)

	// (GET /rss/posts)
	GetRssPosts(c *gin.Context)

	// (POST /users)
	PostUsers(c *gin.Context)

	// (POST /users/token)
	PostUsersToken(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetPostsEditor operation middleware
func (siw *ServerInterfaceWrapper) GetPostsEditor(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsEditor(c)
}

// PostPostsEditor operation middleware
func (siw *ServerInterfaceWrapper) PostPostsEditor(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPostsEditor(c)
}

// DeletePostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePostsEditorId(c, id)
}

// GetPostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsEditorId(c, id)
}

// PutPostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) PutPostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutPostsEditorId(c, id)
}

// GetPostsPublished operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublished(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPublished(c)
}

// GetPostsPublishedId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublishedId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameter("simple", false, "id", c.Param("id"), &id)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPublishedId(c, id)
}

// GetRssPosts operation middleware
func (siw *ServerInterfaceWrapper) GetRssPosts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRssPosts(c)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// PostUsersToken operation middleware
func (siw *ServerInterfaceWrapper) PostUsersToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersToken(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/posts/editor", wrapper.GetPostsEditor)
	router.POST(options.BaseURL+"/posts/editor", wrapper.PostPostsEditor)
	router.DELETE(options.BaseURL+"/posts/editor/:id", wrapper.DeletePostsEditorId)
	router.GET(options.BaseURL+"/posts/editor/:id", wrapper.GetPostsEditorId)
	router.PUT(options.BaseURL+"/posts/editor/:id", wrapper.PutPostsEditorId)
	router.GET(options.BaseURL+"/posts/published", wrapper.GetPostsPublished)
	router.GET(options.BaseURL+"/posts/published/:id", wrapper.GetPostsPublishedId)
	router.GET(options.BaseURL+"/rss/posts", wrapper.GetRssPosts)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.POST(options.BaseURL+"/users/token", wrapper.PostUsersToken)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYTXMiNxD9KyolVTlkyrBZ58ItziZbTg5x+aNycHEQTAPazEja7h5jQs1/T7WEZzww",
	"GNu7TrybE0Jqtbrf635IrPXUl8E7cEx6tNY0XUBp4vDME79jL8OAPgCyhbiQGwb55FUAPdLEaN1c15m2",
	"ee80VWVpcNW7xnDL/QuWi/5TbizZSWdt4n0Bxum6zjTCx8oi5Hp0LfHcOWqj2JyZpTRad+Pszp2ffIAp",
	"y1ECwS+5ZY9fNhB7MTiU/BnCjYXly2f/cmw/guYrArz0f4HrzRNug8U03Oy0jmEOGAOXbT2BbxMQzbLG",
	"124UAhBMK7S8upAeTAdOwCDgTxUv2m+/eiwN65H+7c9LyTRaCy5xVTeeF8xB1+LYulnMa4OyvrBlKECd",
	"FH4uyACS9U6P9JujoeTkAzgTrB7pt0fDo6HOdDC8iPEMgiemAcSekIk5xKrNgaZoAyc/74GVKQoVjTM1",
	"8bxQoZoUlhaQK+NylaOZMel4FhrZdpqnjVJ1lHpOC4YUvKMExg/DoXxMvWNw8VgTQmGncf/gA3nXKpiM",
	"LEMZN36LMNMj/c2g1brBRugGW1VeN/AZRLNK+HWz++N3sToevtlN/MqZihce7d+Qi9GPKeKu0aljQGcK",
	"RYA3gAoQPXYKQI+uu9Rfj2upGDMnKaYIkR7XmRaAdw/4GcEwKKMcLCMHOzjHpLeA/lgB8YnPV0/C+BC0",
	"rXrW3Z5grKDeIbgH01cDd511y3+wtnmdzisgSWH35HdxXhmn4NYSWzfvZyPZ3ePjNI89h6YEBqQYX9e1",
	"GKsoeFa+Sn/qTDsThSDOd5HO7lG2rVTj/jZ7NgvHw+Ndoxiw86xmvnL/Sm/sV6bIQqaWC+AFoLL8Hd2T",
	"J48S5wFpehUMfbYmbdrzS+c8VD2cX4XcPKYNz6r/mOFXocBfQe+3Qt109YNXlbb34669rX/WeHvNF5Mn",
	"YvsI8JofuocktYOhmqxSZxwA8n8loy/RGX3sIVFi8GHKnDq/uFAzgFwtbeeCvrcLzonONmtPABKJvr8t",
	"iy6W29y8XDFXFCtr/ZjLstj2XpavopPni3T3RRkM0dJj/zNZYkj1fehR2Vhmrceeh+Xzrt2SsZpGcDbK",
	"3sPEicnVBhI1EUyi4dtdw3OYW+IEqrKkcktmUsCnlHyi5B7Hg+Yt3s/0e3BCq3At9uruTb6H7cvN8ldK",
	"+eeTvs6/Jz2dHNeeVUqfWhnt3PruJyOt1VkzkaSiHtf/BAAA//9S4BjbChUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
