// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// PageDto defines model for PageDto.
type PageDto struct {
	// Items Page items
	Items []interface{} `json:"items"`

	// Page Current page
	Page int64 `json:"page"`

	// TotalPages Total pages
	TotalPages int64 `json:"totalPages"`
}

// PagePostDto defines model for PagePostDto.
type PagePostDto struct {
	Items []PostPreviewDto `json:"items"`

	// Page Current page
	Page int64 `json:"page"`

	// TotalPages Total pages
	TotalPages int64 `json:"totalPages"`
}

// PostDto defines model for PostDto.
type PostDto struct {
	Date     string  `json:"date"`
	Id       string  `json:"id"`
	Keywords *string `json:"keywords,omitempty"`
	Summary  string  `json:"summary"`
	Text     string  `json:"text"`
	Title    string  `json:"title"`
	Visible  bool    `json:"visible"`
}

// PostEditorDto defines model for PostEditorDto.
type PostEditorDto struct {
	Date     *string `json:"date,omitempty"`
	Id       *string `json:"id,omitempty"`
	Keywords *string `json:"keywords,omitempty"`
	Summary  string  `json:"summary"`
	Text     string  `json:"text"`
	Title    string  `json:"title"`
	Visible  bool    `json:"visible"`
}

// PostPreviewDto defines model for PostPreviewDto.
type PostPreviewDto struct {
	Date    string `json:"date"`
	Id      string `json:"id"`
	Summary string `json:"summary"`
	Title   string `json:"title"`
	Visible bool   `json:"visible"`
}

// UserTokenDto defines model for UserTokenDto.
type UserTokenDto struct {
	Expires int    `json:"expires"`
	Token   string `json:"token"`
}

// GetPostsEditorParams defines parameters for GetPostsEditor.
type GetPostsEditorParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// GetPostsPublishedParams defines parameters for GetPostsPublished.
type GetPostsPublishedParams struct {
	// Page Page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostUsersTokenJSONBody defines parameters for PostUsersToken.
type PostUsersTokenJSONBody struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostPostsEditorJSONRequestBody defines body for PostPostsEditor for application/json ContentType.
type PostPostsEditorJSONRequestBody = PostEditorDto

// PutPostsEditorIdJSONRequestBody defines body for PutPostsEditorId for application/json ContentType.
type PutPostsEditorIdJSONRequestBody = PostEditorDto

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody

// PostUsersTokenJSONRequestBody defines body for PostUsersToken for application/json ContentType.
type PostUsersTokenJSONRequestBody PostUsersTokenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /posts/editor)
	GetPostsEditor(c *gin.Context, params GetPostsEditorParams)

	// (POST /posts/editor)
	PostPostsEditor(c *gin.Context)

	// (DELETE /posts/editor/{id})
	DeletePostsEditorId(c *gin.Context, id string)

	// (GET /posts/editor/{id})
	GetPostsEditorId(c *gin.Context, id string)

	// (PUT /posts/editor/{id})
	PutPostsEditorId(c *gin.Context, id string)

	// (GET /posts/published)
	GetPostsPublished(c *gin.Context, params GetPostsPublishedParams)

	// (GET /posts/published/{id})
	GetPostsPublishedId(c *gin.Context, id string)

	// (GET /rss/posts)
	GetRssPosts(c *gin.Context)

	// (POST /users)
	PostUsers(c *gin.Context)

	// (POST /users/token)
	PostUsersToken(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetPostsEditor operation middleware
func (siw *ServerInterfaceWrapper) GetPostsEditor(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsEditorParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsEditor(c, params)
}

// PostPostsEditor operation middleware
func (siw *ServerInterfaceWrapper) PostPostsEditor(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPostsEditor(c)
}

// DeletePostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) DeletePostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeletePostsEditorId(c, id)
}

// GetPostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsEditorId(c, id)
}

// PutPostsEditorId operation middleware
func (siw *ServerInterfaceWrapper) PutPostsEditorId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutPostsEditorId(c, id)
}

// GetPostsPublished operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublished(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsPublishedParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPublished(c, params)
}

// GetPostsPublishedId operation middleware
func (siw *ServerInterfaceWrapper) GetPostsPublishedId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPostsPublishedId(c, id)
}

// GetRssPosts operation middleware
func (siw *ServerInterfaceWrapper) GetRssPosts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRssPosts(c)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// PostUsersToken operation middleware
func (siw *ServerInterfaceWrapper) PostUsersToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersToken(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/posts/editor", wrapper.GetPostsEditor)
	router.POST(options.BaseURL+"/posts/editor", wrapper.PostPostsEditor)
	router.DELETE(options.BaseURL+"/posts/editor/:id", wrapper.DeletePostsEditorId)
	router.GET(options.BaseURL+"/posts/editor/:id", wrapper.GetPostsEditorId)
	router.PUT(options.BaseURL+"/posts/editor/:id", wrapper.PutPostsEditorId)
	router.GET(options.BaseURL+"/posts/published", wrapper.GetPostsPublished)
	router.GET(options.BaseURL+"/posts/published/:id", wrapper.GetPostsPublishedId)
	router.GET(options.BaseURL+"/rss/posts", wrapper.GetRssPosts)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.POST(options.BaseURL+"/users/token", wrapper.PostUsersToken)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYTXPjNg/+Kxy+70wP1cTe3bQH35puu5P2sJ58TA+ZHCgLtrmRSC0IxXE9+u8dgrJk",
	"xXTszUebyZ6iEBAIPA/wkPJKTmxRWgOGnBytpJvMoVD8OFYz+EjWP5ZoS0DSwAZNUPBDBm6CuiRtjRyx",
	"vwi2pPWpE0nLEuRIKkS1lHUiSzWD7bd/rRDBkGBrIqcWC0VyJLWhn49lG0Ubghmgj0OWVO43jeRy4W0c",
	"yx0SrE4kwtdKI2RydCWbHDY2WBd0XSdc59g6arBRef55KkdXK/l/hKkcyf8NOkgHDZ6DNZh1shPN9uHB",
	"ONbRGOFWwyKEuwdvt2DTLzAhWXPKXbr9zTNFzEXzjiPUZuaj6iy6fAPLhcXMRY2uKgqFy6iN4I7iBk15",
	"PIVb7XTas6XW5qDMFl86k+tAXRbNnkmosQt3vYVQwOe3TJPFN4zSToD2IbPRb0+G5sHqX64VDuiBSwd4",
	"YW/AROuEu1IjbDLaU6IbMJHE7xPAbkkbazsLDxBMKtS0PPcDHzZMQSHgLxXNu/9+X0vaH39d+ErZ2+PC",
	"1k7i5kSlrH1gbaZcV4OyPNdFmYM4ye3MIwPognS+O3rva7IlGFVqOZIfjoZHQ+l1m+acz6C0jtwAeGD8",
	"wgxoW4I/AQmV54KdE5FamouySnPt5pAJZTKRoZqS11YPtPKvnWbhRd91Lgwkb4yqAAJ0LLORU8dURcpV",
	"a7/0tQIm3SiGpFHzoKAxAutrz5MrrXEB8PfDof8zsYbAcGmqLHM94RwHX5w13VG5V7A3TgvmoZ/+5z89",
	"2MfDd9sAXhpV0dyi/hsy7/RTyKrvdGoI0KhcOMBbQAGIFnuNxJhtttDVtS+Y1MzDyQMezjVPVORcRlAE",
	"QgkDC+Zyiy+WiB5hvunB0YnNls+HY0+i6/5sEVZQb5EYwfTVwF0n/TEarHRWh/1yoMj96COvC2UE3GlH",
	"2szibAS/DT5Os70jZB0JFk4eHz/n3fTweh/pyCy1irdjlB7NwvHwOHLT9AkbS2JqK/OvzMZuhWMWErGY",
	"A80BhaYf3IbMWfR57pG4V8HQsw3p04XulXBeVhHOL8tMHTKG4+o/ZvhVKPAbmP1OqNupfvDK080+v7Vz",
	"9MdttO/hgvONHB1AQntgPiTNPS5EugwTtoeQ70qOX2LCYuyhc4HBhykz4uz8XEwBMrHQvQ+GndN05ty4",
	"sX0DkOjcj3dF3sfyPjcv18yV485aHXLp9r7RS/clB3m82Pe/cEvl3MJi/LPd5xD6e99HbuuZdBEjH7qP",
	"u777isWEwWlOiAgTJyoTDSQi9Ziw44dtxzOYaUcBVKGdyLRTaQ5PaflAyQbHg/a3gTjTn8B4Wj3X3l+s",
	"fyPYwfZFY36jlD+f9PV+zYlMMtse1UpP7YxubbU+MoKtTtqFIBX1df1PAAAA//+2vpN/nxcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
