/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorDto
 */
export interface ErrorDto {
    /**
     * Error message
     * @type {string}
     * @memberof ErrorDto
     */
    message: string;
    /**
     * Error message definition
     * @type {string}
     * @memberof ErrorDto
     */
    messageDefinition: string;
}

/**
 * Check if a given object implements the ErrorDto interface.
 */
export function instanceOfErrorDto(value: object): value is ErrorDto {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('messageDefinition' in value) || value['messageDefinition'] === undefined) return false;
    return true;
}

export function ErrorDtoFromJSON(json: any): ErrorDto {
    return ErrorDtoFromJSONTyped(json, false);
}

export function ErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'messageDefinition': json['messageDefinition'],
    };
}

  export function ErrorDtoToJSON(json: any): ErrorDto {
      return ErrorDtoToJSONTyped(json, false);
  }

  export function ErrorDtoToJSONTyped(value?: ErrorDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'messageDefinition': value['messageDefinition'],
    };
}

