/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageDto
 */
export interface PageDto {
    /**
     * Current page
     * @type {number}
     * @memberof PageDto
     */
    page: number;
    /**
     * Total pages
     * @type {number}
     * @memberof PageDto
     */
    totalPages: number;
    /**
     * Page items
     * @type {Array<any>}
     * @memberof PageDto
     */
    items: Array<any>;
}

/**
 * Check if a given object implements the PageDto interface.
 */
export function instanceOfPageDto(value: object): value is PageDto {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function PageDtoFromJSON(json: any): PageDto {
    return PageDtoFromJSONTyped(json, false);
}

export function PageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'totalPages': json['totalPages'],
        'items': json['items'],
    };
}

  export function PageDtoToJSON(json: any): PageDto {
      return PageDtoToJSONTyped(json, false);
  }

  export function PageDtoToJSONTyped(value?: PageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'totalPages': value['totalPages'],
        'items': value['items'],
    };
}

