/* tslint:disable */
/* eslint-disable */
/**
 * Simple Blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostPreviewDto } from './PostPreviewDto';
import {
    PostPreviewDtoFromJSON,
    PostPreviewDtoFromJSONTyped,
    PostPreviewDtoToJSON,
} from './PostPreviewDto';

/**
 * 
 * @export
 * @interface PagePostDto
 */
export interface PagePostDto {
    /**
     * Current page
     * @type {number}
     * @memberof PagePostDto
     */
    page: number;
    /**
     * Total pages
     * @type {number}
     * @memberof PagePostDto
     */
    totalPages: number;
    /**
     * 
     * @type {Array<PostPreviewDto>}
     * @memberof PagePostDto
     */
    items: Array<PostPreviewDto>;
}

/**
 * Check if a given object implements the PagePostDto interface.
 */
export function instanceOfPagePostDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "totalPages" in value;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function PagePostDtoFromJSON(json: any): PagePostDto {
    return PagePostDtoFromJSONTyped(json, false);
}

export function PagePostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePostDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'totalPages': json['totalPages'],
        'items': ((json['items'] as Array<any>).map(PostPreviewDtoFromJSON)),
    };
}

export function PagePostDtoToJSON(value?: PagePostDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'totalPages': value.totalPages,
        'items': ((value.items as Array<any>).map(PostPreviewDtoToJSON)),
    };
}

