name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file service/Dockerfile --tag ghcr.io/${{ github.repository }}/simple-blog-service:latest
        docker push ghcr.io/${{ github.repository }}/simple-blog-service:latest
