name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          push: true
      - name: Install kubectl
        uses: azure/setup-kubectl@v5
      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Install helm
        uses: azure/setup-helm@v5
      - name: Set up network
        run: |
          sudo apt install -y wireguard
          echo "${{ secrets.WG_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
      - name: Deploy
        run: |
          helm upgrade --install service ./helm \
            --namespace simple-blog \
            --create-simple-blog \
            --set image.tag="${{ github.ref_name }}" \
            -f helm/values.yaml
